server {
  listen 80;
  server_name _;
  root /usr/share/nginx/html;
  index index.html;

  location = /sw.js {
    add_header Cache-Control "no-cache, no-store, must-revalidate";
    try_files $uri =404;
  }

  location = /manifest.webmanifest {
    add_header Cache-Control "no-cache";
    try_files $uri =404;
  }

  location / {
    try_files $uri $uri/ /index.html;
  }

  location /api/ {
    proxy_pass http://backend:7659/api/;
	proxy_set_header Host $http_host;
	proxy_set_header X-Forwarded-Host $http_host;
	proxy_set_header X-Forwarded-Proto $scheme;
  }

  location /health {
    proxy_pass http://backend:7659/health;
	proxy_set_header Host $http_host;
	proxy_set_header X-Forwarded-Host $http_host;
	proxy_set_header X-Forwarded-Proto $scheme;
  }
}
