package storage

import (
	"context"
	"database/sql"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"
)

// Backup file names are generated by Kikoto only. The kind separates routine
// backups from the snapshot taken before a schema upgrade, so pruning one kind
// never removes the other.
const (
	BackupKindScheduled    = "scheduled"
	BackupKindManual       = "manual"
	BackupKindPreMigration = "pre-migration"

	backupFilePrefix  = "kikoto-"
	backupFileSuffix  = ".db"
	backupPartialName = ".partial"
	backupTimeLayout  = "20060102-150405"
)

// BackupFile describes one completed database backup.
type BackupFile struct {
	Name      string    `json:"name"`
	Kind      string    `json:"kind"`
	SizeBytes int64     `json:"sizeBytes"`
	CreatedAt time.Time `json:"createdAt"`
}

// BackupFileName returns the name of a backup of the given kind taken at now.
// The detail, such as a schema version range, is appended when present.
func BackupFileName(kind string, now time.Time, detail string) string {
	name := backupFilePrefix + kind + "-" + now.UTC().Format(backupTimeLayout)
	if detail = strings.TrimSpace(detail); detail != "" {
		name += "-" + detail
	}
	return name + backupFileSuffix
}

// BackupInto writes a transactionally consistent copy of db to path. VACUUM
// INTO reads one snapshot, so concurrent writers are neither blocked for the
// whole copy nor partially included. The copy is written beside its final name
// and verified before it is renamed into place, so a backup file that exists is
// always complete. Backups contain password hashes and sessions, so the file is
// readable by its owner only.
func BackupInto(ctx context.Context, db *sql.DB, path string) (int64, error) {
	if db == nil {
		return 0, errors.New("back up database: nil database")
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o700); err != nil {
		return 0, fmt.Errorf("create backup directory: %w", err)
	}
	partial := path + backupPartialName
	if err := os.Remove(partial); err != nil && !errors.Is(err, os.ErrNotExist) {
		return 0, fmt.Errorf("remove incomplete backup: %w", err)
	}
	if _, err := db.ExecContext(ctx, "VACUUM INTO ?", partial); err != nil {
		_ = os.Remove(partial)
		return 0, fmt.Errorf("write database backup: %w", err)
	}
	if err := verifyBackupFile(ctx, partial); err != nil {
		_ = os.Remove(partial)
		return 0, err
	}
	if err := os.Chmod(partial, 0o600); err != nil {
		_ = os.Remove(partial)
		return 0, fmt.Errorf("restrict backup permissions: %w", err)
	}
	if err := os.Rename(partial, path); err != nil {
		_ = os.Remove(partial)
		return 0, fmt.Errorf("publish database backup: %w", err)
	}
	info, err := os.Stat(path)
	if err != nil {
		return 0, err
	}
	return info.Size(), nil
}

func verifyBackupFile(ctx context.Context, path string) error {
	absolute, err := filepath.Abs(path)
	if err != nil {
		return err
	}
	backup, err := sql.Open("sqlite", "file:"+filepath.ToSlash(absolute)+"?mode=ro")
	if err != nil {
		return fmt.Errorf("open database backup: %w", err)
	}
	defer func() { _ = backup.Close() }()
	var result string
	if err := backup.QueryRowContext(ctx, "PRAGMA quick_check").Scan(&result); err != nil {
		return fmt.Errorf("verify database backup: %w", err)
	}
	if result != "ok" {
		return fmt.Errorf("verify database backup: %s", result)
	}
	return nil
}

// ListBackups returns completed backups in dir, newest first. A missing
// directory has no backups.
func ListBackups(dir string) ([]BackupFile, error) {
	entries, err := os.ReadDir(dir)
	if errors.Is(err, os.ErrNotExist) {
		return []BackupFile{}, nil
	}
	if err != nil {
		return nil, err
	}
	backups := []BackupFile{}
	for _, entry := range entries {
		if !entry.Type().IsRegular() {
			continue
		}
		kind, createdAt, ok := parseBackupFileName(entry.Name())
		if !ok {
			continue
		}
		info, err := entry.Info()
		if err != nil {
			continue
		}
		backups = append(backups, BackupFile{Name: entry.Name(), Kind: kind, SizeBytes: info.Size(), CreatedAt: createdAt})
	}
	sort.Slice(backups, func(i, j int) bool {
		if !backups[i].CreatedAt.Equal(backups[j].CreatedAt) {
			return backups[i].CreatedAt.After(backups[j].CreatedAt)
		}
		return backups[i].Name > backups[j].Name
	})
	return backups, nil
}

// PruneBackups keeps the newest keep backups of kind in dir and removes the
// rest. Other kinds and files Kikoto did not name are never touched.
func PruneBackups(dir string, kind string, keep int) (int, error) {
	backups, err := ListBackups(dir)
	if err != nil {
		return 0, err
	}
	kept, removed := 0, 0
	for _, backup := range backups {
		if backup.Kind != kind {
			continue
		}
		if kept < keep {
			kept++
			continue
		}
		if err := os.Remove(filepath.Join(dir, backup.Name)); err != nil && !errors.Is(err, os.ErrNotExist) {
			return removed, err
		}
		removed++
	}
	return removed, nil
}

func parseBackupFileName(name string) (string, time.Time, bool) {
	if !strings.HasPrefix(name, backupFilePrefix) || !strings.HasSuffix(name, backupFileSuffix) {
		return "", time.Time{}, false
	}
	rest := strings.TrimSuffix(strings.TrimPrefix(name, backupFilePrefix), backupFileSuffix)
	for _, kind := range []string{BackupKindPreMigration, BackupKindScheduled, BackupKindManual} {
		if !strings.HasPrefix(rest, kind+"-") {
			continue
		}
		stamp := strings.TrimPrefix(rest, kind+"-")
		if len(stamp) < len(backupTimeLayout) {
			return "", time.Time{}, false
		}
		createdAt, err := time.ParseInLocation(backupTimeLayout, stamp[:len(backupTimeLayout)], time.UTC)
		if err != nil {
			return "", time.Time{}, false
		}
		return kind, createdAt, true
	}
	return "", time.Time{}, false
}
