// Command schema-baseline generates a fresh-install SQL snapshot from the
// numbered migration chain. Existing databases must continue to use the
// numbered migrations because their data transformations are not represented
// by a schema dump.
package main

import (
	"database/sql"
	"encoding/hex"
	"errors"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strconv"
	"strings"

	_ "modernc.org/sqlite"
)

var (
	migrationPattern      = regexp.MustCompile(`^([0-9]{3})_[a-z0-9][a-z0-9_]*\.sql$`)
	releaseVersionPattern = regexp.MustCompile(`^v[0-9]+\.[0-9]+\.[0-9]+$`)
)

type schemaObject struct {
	kind string
	name string
	sql  string
}

type column struct {
	name        string
	defaultSQL  sql.NullString
	primaryKey  int
	columnIndex int
}

type seedTableData struct {
	name    string
	columns []column
	rows    [][]any
}

func main() {
	migrationsDir := flag.String("migrations", ".", "directory containing numbered migration SQL files")
	versionFile := flag.String("version-file", "", "path to the Kikoto VERSION file")
	output := flag.String("output", "", "output baseline SQL path (defaults to baseline/<schema-version>_<release>.sql)")
	flag.Parse()

	release, err := readReleaseVersion(*versionFile)
	if err != nil {
		fatal(err)
	}
	files, current, err := numberedFiles(*migrationsDir)
	if err != nil {
		fatal(err)
	}
	db, err := sql.Open("sqlite", "file::memory:?mode=memory&cache=shared&_pragma=foreign_keys(1)")
	if err != nil {
		fatal(err)
	}
	defer db.Close()
	db.SetMaxOpenConns(1)
	db.SetMaxIdleConns(1)
	if _, err := db.Exec("PRAGMA foreign_keys = ON"); err != nil {
		fatal(err)
	}
	for _, file := range files {
		contents, err := os.ReadFile(filepath.Join(*migrationsDir, file))
		if err != nil {
			fatal(err)
		}
		if _, err := db.Exec(string(contents)); err != nil {
			fatal(fmt.Errorf("apply %s: %w", file, err))
		}
	}
	if err := verifyForeignKeys(db); err != nil {
		fatal(err)
	}
	outputPath := *output
	if outputPath == "" {
		outputPath = filepath.Join(*migrationsDir, "baseline", fmt.Sprintf("%03d_%s.sql", current, release))
	}
	contents, err := dumpDatabase(db, current, release)
	if err != nil {
		fatal(err)
	}
	if err := os.MkdirAll(filepath.Dir(outputPath), 0o755); err != nil {
		fatal(err)
	}
	if err := os.WriteFile(outputPath, []byte(contents), 0o644); err != nil {
		fatal(err)
	}
	fmt.Printf("wrote %s for Kikoto %s schema version %03d\n", outputPath, release, current)
}

func readReleaseVersion(path string) (string, error) {
	if strings.TrimSpace(path) == "" {
		return "", errors.New("schema baseline generation requires -version-file")
	}
	contents, err := os.ReadFile(path)
	if err != nil {
		return "", fmt.Errorf("read VERSION file: %w", err)
	}
	version := strings.TrimSpace(string(contents))
	if !releaseVersionPattern.MatchString(version) {
		return "", fmt.Errorf("VERSION must use v<major>.<minor>.<patch>, got %q", version)
	}
	return version, nil
}

func numberedFiles(dir string) ([]string, int, error) {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return nil, 0, err
	}
	byVersion := make(map[int]string)
	for _, entry := range entries {
		if entry.IsDir() || !strings.HasSuffix(entry.Name(), ".sql") {
			continue
		}
		matches := migrationPattern.FindStringSubmatch(entry.Name())
		if matches == nil {
			return nil, 0, fmt.Errorf("invalid migration filename %q", entry.Name())
		}
		version, _ := strconv.Atoi(matches[1])
		if previous, exists := byVersion[version]; exists {
			return nil, 0, fmt.Errorf("duplicate migration version %03d: %s and %s", version, previous, entry.Name())
		}
		byVersion[version] = entry.Name()
	}
	versions := make([]int, 0, len(byVersion))
	for version := range byVersion {
		versions = append(versions, version)
	}
	sort.Ints(versions)
	files := make([]string, 0, len(versions))
	for index, version := range versions {
		if version != index+1 {
			return nil, 0, fmt.Errorf("migration chain has a gap at %03d", index+1)
		}
		files = append(files, byVersion[version])
	}
	if len(files) == 0 {
		return nil, 0, fmt.Errorf("no numbered migrations in %s", dir)
	}
	return files, versions[len(versions)-1], nil
}

func dumpDatabase(db *sql.DB, version int, release string) (string, error) {
	objects, err := readSchemaObjects(db)
	if err != nil {
		return "", err
	}
	var tables, indexes, views, triggers []schemaObject
	for _, object := range objects {
		switch object.kind {
		case "table":
			tables = append(tables, object)
		case "index":
			indexes = append(indexes, object)
		case "view":
			views = append(views, object)
		case "trigger":
			triggers = append(triggers, object)
		}
	}
	byName := func(objects []schemaObject) {
		sort.Slice(objects, func(i, j int) bool { return objects[i].name < objects[j].name })
	}
	byName(tables)
	byName(indexes)
	byName(views)
	byName(triggers)

	var out strings.Builder
	fmt.Fprintf(&out, "-- Generated by go run ./cmd/schema-baseline.\n-- Fresh-install baseline for Kikoto %s (schema version %03d).\n-- Do not use this file to upgrade an existing database.\n\n", release, version)
	for _, object := range tables {
		fmt.Fprintf(&out, "%s;\n\n", object.sql)
	}
	seed, err := dumpSeedData(db, tables)
	if err != nil {
		return "", err
	}
	for _, statement := range seed {
		fmt.Fprintf(&out, "%s;\n", statement)
	}
	if len(seed) > 0 {
		out.WriteString("\n")
	}
	for _, object := range indexes {
		fmt.Fprintf(&out, "%s;\n\n", object.sql)
	}
	for _, object := range views {
		fmt.Fprintf(&out, "%s;\n\n", object.sql)
	}
	for _, object := range triggers {
		fmt.Fprintf(&out, "%s;\n\n", object.sql)
	}
	return strings.TrimRight(out.String(), "\n") + "\n", nil
}

func readSchemaObjects(db *sql.DB) ([]schemaObject, error) {
	rows, err := db.Query(`
		SELECT type, name, sql
		FROM sqlite_schema
		WHERE sql IS NOT NULL
		  AND name NOT LIKE 'sqlite_%'
		  AND name NOT IN ('schema_migration', 'schema_state')
	`)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var objects []schemaObject
	for rows.Next() {
		var object schemaObject
		if err := rows.Scan(&object.kind, &object.name, &object.sql); err != nil {
			return nil, err
		}
		objects = append(objects, object)
	}
	return objects, rows.Err()
}

func dumpSeedData(db *sql.DB, tables []schemaObject) ([]string, error) {
	// A fresh database only has deterministic reference/bootstrap rows. User
	// rows cannot exist yet, so dumping every non-empty table preserves all
	// migration-provided seeds without maintaining a second hand-written list.
	var data []seedTableData
	for _, table := range tables {
		columns, err := tableColumns(db, table.name)
		if err != nil {
			return nil, err
		}
		selectColumns := make([]column, 0, len(columns))
		for _, column := range columns {
			// Timestamp defaults are intentionally evaluated on the target
			// database rather than freezing the generator's wall clock.
			if column.defaultSQL.Valid && strings.Contains(strings.ToUpper(column.defaultSQL.String), "CURRENT_TIMESTAMP") {
				continue
			}
			selectColumns = append(selectColumns, column)
		}
		if len(selectColumns) == 0 {
			continue
		}
		quoted := make([]string, len(selectColumns))
		for i, column := range selectColumns {
			quoted[i] = quoteIdentifier(column.name)
		}
		rows, err := db.Query("SELECT " + strings.Join(quoted, ", ") + " FROM " + quoteIdentifier(table.name))
		if err != nil {
			return nil, fmt.Errorf("read seed table %s: %w", table.name, err)
		}
		var tableRows [][]any
		for rows.Next() {
			values := make([]any, len(selectColumns))
			pointers := make([]any, len(values))
			for i := range values {
				pointers[i] = &values[i]
			}
			if err := rows.Scan(pointers...); err != nil {
				rows.Close()
				return nil, fmt.Errorf("read seed table %s: %w", table.name, err)
			}
			tableRows = append(tableRows, values)
		}
		if err := rows.Close(); err != nil {
			return nil, fmt.Errorf("read seed table %s: %w", table.name, err)
		}
		if len(tableRows) > 0 {
			data = append(data, seedTableData{name: table.name, columns: selectColumns, rows: tableRows})
		}
	}
	orderedData, err := orderSeedData(db, data)
	if err != nil {
		return nil, err
	}
	data = orderedData
	var statements []string
	for _, table := range data {
		columnNames := make([]string, len(table.columns))
		for i, column := range table.columns {
			columnNames[i] = quoteIdentifier(column.name)
		}
		rowSQL := make([]string, len(table.rows))
		for i, row := range table.rows {
			values := make([]string, len(row))
			for j, value := range row {
				values[j] = quoteValue(value)
			}
			rowSQL[i] = "INSERT INTO " + quoteIdentifier(table.name) + " (" + strings.Join(columnNames, ", ") + ") VALUES (" + strings.Join(values, ", ") + ")"
		}
		sort.Strings(rowSQL)
		statements = append(statements, rowSQL...)
	}
	return statements, nil
}

func orderSeedData(db *sql.DB, data []seedTableData) ([]seedTableData, error) {
	byName := make(map[string]seedTableData, len(data))
	for _, table := range data {
		byName[table.name] = table
	}
	indegree := make(map[string]int, len(data))
	dependents := make(map[string][]string, len(data))
	for _, table := range data {
		indegree[table.name] = 0
	}
	for _, table := range data {
		rows, err := db.Query("PRAGMA foreign_key_list(" + quoteIdentifier(table.name) + ")")
		if err != nil {
			return nil, fmt.Errorf("inspect seed dependencies for %s: %w", table.name, err)
		}
		dependencies := make(map[string]struct{})
		for rows.Next() {
			var id, sequence int
			var referenced, from, to, onUpdate, onDelete, match string
			if err := rows.Scan(&id, &sequence, &referenced, &from, &to, &onUpdate, &onDelete, &match); err != nil {
				rows.Close()
				return nil, fmt.Errorf("inspect seed dependencies for %s: %w", table.name, err)
			}
			if referenced != table.name {
				if _, exists := byName[referenced]; exists {
					dependencies[referenced] = struct{}{}
				}
			}
		}
		if err := rows.Close(); err != nil {
			return nil, fmt.Errorf("inspect seed dependencies for %s: %w", table.name, err)
		}
		for dependency := range dependencies {
			indegree[table.name]++
			dependents[dependency] = append(dependents[dependency], table.name)
		}
	}
	queue := make([]string, 0, len(data))
	for name, degree := range indegree {
		if degree == 0 {
			queue = append(queue, name)
		}
	}
	sort.Strings(queue)
	ordered := make([]seedTableData, 0, len(data))
	for len(queue) > 0 {
		name := queue[0]
		queue = queue[1:]
		ordered = append(ordered, byName[name])
		children := dependents[name]
		sort.Strings(children)
		for _, child := range children {
			indegree[child]--
			if indegree[child] == 0 {
				queue = append(queue, child)
			}
		}
		sort.Strings(queue)
	}
	if len(ordered) != len(data) {
		return nil, errors.New("seed data contains a foreign-key cycle")
	}
	return ordered, nil
}

func tableColumns(db *sql.DB, table string) ([]column, error) {
	rows, err := db.Query("PRAGMA table_info(" + quoteIdentifier(table) + ")")
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var columns []column
	for rows.Next() {
		var column column
		var notNull int
		var columnType string
		if err := rows.Scan(&column.columnIndex, &column.name, &columnType, &notNull, &column.defaultSQL, &column.primaryKey); err != nil {
			return nil, err
		}
		columns = append(columns, column)
	}
	return columns, rows.Err()
}

func quoteIdentifier(value string) string {
	return `"` + strings.ReplaceAll(value, `"`, `""`) + `"`
}

func quoteValue(value any) string {
	switch value := value.(type) {
	case nil:
		return "NULL"
	case int64:
		return strconv.FormatInt(value, 10)
	case float64:
		return strconv.FormatFloat(value, 'g', -1, 64)
	case []byte:
		return "X'" + hex.EncodeToString(value) + "'"
	case string:
		return "'" + strings.ReplaceAll(value, "'", "''") + "'"
	default:
		return "'" + strings.ReplaceAll(fmt.Sprint(value), "'", "''") + "'"
	}
}

func verifyForeignKeys(db *sql.DB) error {
	rows, err := db.Query("PRAGMA foreign_key_check")
	if err != nil {
		return err
	}
	defer rows.Close()
	if rows.Next() {
		return fmt.Errorf("foreign key check failed while generating baseline")
	}
	return rows.Err()
}

func fatal(err error) {
	fmt.Fprintln(os.Stderr, err)
	os.Exit(1)
}
