-- Generated by go run ./cmd/schema-baseline.
-- Fresh-install baseline for schema version 030.
-- Do not use this file to upgrade an existing database.

CREATE TABLE app_setting (
  key TEXT PRIMARY KEY,
  value_json TEXT NOT NULL,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE audit_log (
  id INTEGER PRIMARY KEY,
  actor_user_id INTEGER REFERENCES user_account(id) ON DELETE SET NULL,
  action TEXT NOT NULL,
  target_type TEXT NOT NULL DEFAULT '',
  target_id TEXT NOT NULL DEFAULT '',
  detail_json TEXT NOT NULL DEFAULT '{}',
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE availability_watch (
  id INTEGER PRIMARY KEY,
  owner_user_id INTEGER NOT NULL UNIQUE REFERENCES user_account(id) ON DELETE CASCADE,
  enabled INTEGER NOT NULL DEFAULT 0,
  interval_minutes INTEGER NOT NULL DEFAULT 60 CHECK(interval_minutes BETWEEN 5 AND 10080),
  action TEXT NOT NULL DEFAULT 'monitor' CHECK(action IN ('monitor', 'track', 'fetch', 'track_fetch')),
  source_id INTEGER REFERENCES file_source(id) ON DELETE SET NULL,
  exclude_extensions_json TEXT NOT NULL DEFAULT '["wav"]',
  revision INTEGER NOT NULL DEFAULT 1,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE availability_watch_outbox (
  id INTEGER PRIMARY KEY,
  target_id INTEGER NOT NULL REFERENCES availability_watch_target(id) ON DELETE CASCADE,
  availability_epoch INTEGER NOT NULL,
  action TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'pending' CHECK(status IN ('pending', 'running', 'succeeded', 'failed')),
  retry_count INTEGER NOT NULL DEFAULT 0,
  next_attempt_at TEXT,
  error_message TEXT NOT NULL DEFAULT '',
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(target_id, availability_epoch, action)
);

CREATE TABLE availability_watch_target (
  id INTEGER PRIMARY KEY,
  watch_id INTEGER NOT NULL REFERENCES availability_watch(id) ON DELETE CASCADE,
  work_code TEXT NOT NULL,
  active INTEGER NOT NULL DEFAULT 1,
  state TEXT NOT NULL DEFAULT 'monitoring' CHECK(state IN ('monitoring', 'ready', 'action_queued', 'completed', 'error', 'disabled')),
  next_check_at TEXT,
  last_checked_at TEXT,
  last_status TEXT NOT NULL DEFAULT '',
  last_error TEXT NOT NULL DEFAULT '',
  available_source_id INTEGER REFERENCES file_source(id) ON DELETE SET NULL,
  availability_epoch INTEGER NOT NULL DEFAULT 0,
  track_run_id INTEGER REFERENCES workflow_run(id) ON DELETE SET NULL,
  fetch_run_id INTEGER REFERENCES workflow_run(id) ON DELETE SET NULL,
  revision INTEGER NOT NULL DEFAULT 1,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(watch_id, work_code)
);

CREATE TABLE favorite_list (
  id INTEGER PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES user_account(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  description TEXT NOT NULL DEFAULT '',
  sort_order INTEGER NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, kind TEXT NOT NULL DEFAULT 'user' CHECK(kind IN ('marked', 'user')),
  UNIQUE(user_id, name)
);

CREATE TABLE favorite_list_item (
  id INTEGER PRIMARY KEY,
  list_id INTEGER NOT NULL REFERENCES favorite_list(id) ON DELETE CASCADE,
  work_id INTEGER NOT NULL REFERENCES work(id) ON DELETE CASCADE,
  note TEXT NOT NULL DEFAULT '',
  sort_order INTEGER NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(list_id, work_id)
);

CREATE TABLE file_source (
  id INTEGER PRIMARY KEY,
  code TEXT NOT NULL UNIQUE,
  display_name TEXT NOT NULL,
  source_type TEXT NOT NULL,
  priority INTEGER NOT NULL DEFAULT 100,
  enabled INTEGER NOT NULL DEFAULT 1,
  config_json TEXT NOT NULL DEFAULT '{}',
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE file_source_endpoint (
  id INTEGER PRIMARY KEY,
  file_source_id INTEGER NOT NULL REFERENCES file_source(id) ON DELETE CASCADE,
  base_url TEXT NOT NULL DEFAULT '',
  api_url TEXT NOT NULL DEFAULT '',
  fallback_url TEXT NOT NULL DEFAULT '',
  auth_type TEXT NOT NULL DEFAULT 'none',
  credential_ref TEXT NOT NULL DEFAULT '',
  health_status TEXT NOT NULL DEFAULT 'unknown',
  last_checked_at TEXT
, work_url_template TEXT NOT NULL DEFAULT '/work/{code}', restrict_outbound_hosts INTEGER NOT NULL DEFAULT 0 CHECK(restrict_outbound_hosts IN (0, 1)), allowed_host_patterns_json TEXT NOT NULL DEFAULT '[]' CHECK(json_valid(allowed_host_patterns_json)));

CREATE TABLE filesystem_trigger_state (
  trigger_id INTEGER PRIMARY KEY REFERENCES workflow_trigger(id) ON DELETE CASCADE,
  watched_directory_count INTEGER NOT NULL DEFAULT 0,
  last_event_at TEXT,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE logical_work (
  id INTEGER PRIMARY KEY,
  canonical_work_id INTEGER REFERENCES work(id) ON DELETE SET NULL,
  canonical_code TEXT NOT NULL UNIQUE,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE media_file_location (
  id INTEGER PRIMARY KEY,
  media_item_id INTEGER NOT NULL REFERENCES media_item(id) ON DELETE CASCADE,
  file_source_id INTEGER NOT NULL REFERENCES file_source(id) ON DELETE CASCADE,
  location_type TEXT NOT NULL,
  path TEXT NOT NULL DEFAULT '',
  stream_url TEXT NOT NULL DEFAULT '',
  download_url TEXT NOT NULL DEFAULT '',
  remote_hash TEXT NOT NULL DEFAULT '',
  size_bytes INTEGER,
  duration_seconds INTEGER,
  availability TEXT NOT NULL DEFAULT 'unknown',
  last_checked_at TEXT
);

CREATE TABLE media_item (
  id INTEGER PRIMARY KEY,
  work_id INTEGER NOT NULL REFERENCES work(id) ON DELETE CASCADE,
  parent_id INTEGER REFERENCES media_item(id) ON DELETE CASCADE,
  kind TEXT NOT NULL,
  title TEXT NOT NULL,
  disc_no INTEGER,
  track_no INTEGER,
  duration_seconds INTEGER,
  size_bytes INTEGER,
  fingerprint TEXT NOT NULL DEFAULT ''
, has_audio INTEGER);

CREATE TABLE metadata_provider (
  id INTEGER PRIMARY KEY,
  code TEXT NOT NULL UNIQUE,
  display_name TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE metadata_snapshot (
  id INTEGER PRIMARY KEY,
  work_id INTEGER REFERENCES work(id) ON DELETE SET NULL,
  provider_id INTEGER NOT NULL REFERENCES metadata_provider(id),
  external_id TEXT NOT NULL,
  snapshot_json TEXT NOT NULL,
  fetched_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE party (
  id INTEGER PRIMARY KEY,
  party_type TEXT NOT NULL DEFAULT 'circle',
  display_name TEXT NOT NULL,
  sort_name TEXT NOT NULL DEFAULT '',
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE party_catalog_item (
  id INTEGER PRIMARY KEY,
  party_id INTEGER NOT NULL REFERENCES party(id) ON DELETE CASCADE,
  provider_id INTEGER NOT NULL REFERENCES metadata_provider(id),
  primary_code TEXT NOT NULL,
  title TEXT NOT NULL DEFAULT '',
  release_date TEXT,
  url TEXT NOT NULL DEFAULT '',
  catalog_status TEXT NOT NULL DEFAULT 'imported',
  dlsite_available INTEGER NOT NULL DEFAULT 1,
  raw_json TEXT NOT NULL DEFAULT '{}',
  last_seen_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(party_id, provider_id, primary_code)
);

CREATE TABLE party_catalog_refresh_state (
  party_id INTEGER NOT NULL REFERENCES party(id) ON DELETE CASCADE,
  provider_code TEXT NOT NULL,
  last_success_at TEXT,
  last_attempt_at TEXT,
  last_mode TEXT NOT NULL DEFAULT '',
  last_status TEXT NOT NULL DEFAULT '',
  last_run_id INTEGER,
  last_error TEXT NOT NULL DEFAULT '',
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY(party_id, provider_code)
);

CREATE TABLE party_external_id (
  id INTEGER PRIMARY KEY,
  party_id INTEGER NOT NULL REFERENCES party(id) ON DELETE CASCADE,
  provider_id INTEGER NOT NULL REFERENCES metadata_provider(id),
  id_type TEXT NOT NULL,
  external_id TEXT NOT NULL,
  url TEXT NOT NULL DEFAULT '',
  is_primary INTEGER NOT NULL DEFAULT 0,
  UNIQUE(provider_id, id_type, external_id)
);

CREATE TABLE party_metadata_snapshot (
  id INTEGER PRIMARY KEY,
  party_id INTEGER REFERENCES party(id) ON DELETE SET NULL,
  provider_id INTEGER NOT NULL REFERENCES metadata_provider(id),
  external_id TEXT NOT NULL,
  snapshot_json TEXT NOT NULL,
  fetched_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE party_series (
  id INTEGER PRIMARY KEY,
  party_id INTEGER NOT NULL REFERENCES party(id) ON DELETE CASCADE,
  provider_id INTEGER NOT NULL REFERENCES metadata_provider(id),
  title_id TEXT NOT NULL,
  name TEXT NOT NULL,
  url TEXT NOT NULL DEFAULT '',
  declared_works INTEGER NOT NULL DEFAULT 0,
  raw_json TEXT NOT NULL DEFAULT '{}',
  last_seen_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(party_id, provider_id, title_id)
);

CREATE TABLE party_series_work (
  series_id INTEGER NOT NULL REFERENCES party_series(id) ON DELETE CASCADE,
  primary_code TEXT NOT NULL,
  position INTEGER NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY(series_id, primary_code)
);

CREATE TABLE person (
  id INTEGER PRIMARY KEY,
  display_name TEXT NOT NULL,
  sort_name TEXT NOT NULL DEFAULT '',
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(display_name)
);

CREATE TABLE person_alias (
  id INTEGER PRIMARY KEY,
  person_id INTEGER NOT NULL REFERENCES person(id) ON DELETE CASCADE,
  alias TEXT NOT NULL,
  source TEXT NOT NULL DEFAULT '',
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(person_id, alias)
);

CREATE TABLE person_external_id (
  id INTEGER PRIMARY KEY,
  person_id INTEGER NOT NULL REFERENCES person(id) ON DELETE CASCADE,
  provider_id INTEGER NOT NULL REFERENCES metadata_provider(id),
  id_type TEXT NOT NULL,
  external_id TEXT NOT NULL,
  url TEXT NOT NULL DEFAULT '',
  is_primary INTEGER NOT NULL DEFAULT 0,
  UNIQUE(provider_id, id_type, external_id)
);

CREATE TABLE person_merge_review (
  id INTEGER PRIMARY KEY,
  target_person_id INTEGER NOT NULL REFERENCES person(id) ON DELETE CASCADE,
  source_person_id INTEGER NOT NULL,
  target_name TEXT NOT NULL,
  source_name TEXT NOT NULL,
  snapshot_json TEXT NOT NULL DEFAULT '{}',
  status TEXT NOT NULL DEFAULT 'merged',
  undone_at TEXT,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE recommendation_client_session (
  user_id INTEGER NOT NULL REFERENCES user_account(id) ON DELETE CASCADE,
  session_id TEXT NOT NULL CHECK(length(session_id) BETWEEN 1 AND 64),
  generation_id INTEGER REFERENCES recommendation_generation(id) ON DELETE CASCADE,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY(user_id, session_id)
);

CREATE TABLE recommendation_event (
  id INTEGER PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES user_account(id) ON DELETE CASCADE,
  work_id INTEGER REFERENCES work(id) ON DELETE CASCADE,
  event_type TEXT NOT NULL CHECK(event_type IN ('impression', 'open', 'play', 'positive_mark', 'paused_mark', 'reshuffle')),
  context_id TEXT NOT NULL DEFAULT '',
  algorithm_version TEXT NOT NULL DEFAULT '',
  seed INTEGER NOT NULL DEFAULT 0,
  rank INTEGER NOT NULL DEFAULT 0,
  score INTEGER NOT NULL DEFAULT 0 CHECK(score BETWEEN 0 AND 100),
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE recommendation_generation (
  id INTEGER PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES user_account(id) ON DELETE CASCADE,
  algorithm_version TEXT NOT NULL,
  config_json TEXT NOT NULL,
  input_revision INTEGER NOT NULL CHECK(input_revision >= 0),
  user_revision INTEGER NOT NULL CHECK(user_revision >= 0),
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE recommendation_input_revision (
  id INTEGER PRIMARY KEY CHECK(id = 1),
  revision INTEGER NOT NULL DEFAULT 0 CHECK(revision >= 0),
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE recommendation_snapshot (
  generation_id INTEGER NOT NULL REFERENCES recommendation_generation(id) ON DELETE CASCADE,
  work_id INTEGER NOT NULL REFERENCES work(id) ON DELETE CASCADE,
  listening_status TEXT NOT NULL DEFAULT 'none'
    CHECK(listening_status IN ('none', 'want_to_listen', 'listening', 'finished', 'relisten', 'paused')),
  favorite INTEGER NOT NULL DEFAULT 0 CHECK(favorite IN (0, 1)),
  positive_tag_matches INTEGER NOT NULL DEFAULT 0 CHECK(positive_tag_matches >= 0),
  positive_voice_matches INTEGER NOT NULL DEFAULT 0 CHECK(positive_voice_matches >= 0),
  positive_circle_matches INTEGER NOT NULL DEFAULT 0 CHECK(positive_circle_matches >= 0),
  negative_tag_matches INTEGER NOT NULL DEFAULT 0 CHECK(negative_tag_matches >= 0),
  negative_voice_matches INTEGER NOT NULL DEFAULT 0 CHECK(negative_voice_matches >= 0),
  negative_circle_matches INTEGER NOT NULL DEFAULT 0 CHECK(negative_circle_matches >= 0),
  score INTEGER NOT NULL CHECK(score BETWEEN 0 AND 100),
  PRIMARY KEY(generation_id, work_id)
);

CREATE TABLE recommendation_snapshot_state (
  user_id INTEGER PRIMARY KEY REFERENCES user_account(id) ON DELETE CASCADE,
  current_generation_id INTEGER REFERENCES recommendation_generation(id) ON DELETE SET NULL,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE recommendation_user_revision (
  user_id INTEGER PRIMARY KEY REFERENCES user_account(id) ON DELETE CASCADE,
  revision INTEGER NOT NULL DEFAULT 0 CHECK(revision >= 0),
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE remote_fetch_manifest (
  id INTEGER PRIMARY KEY,
  workflow_run_id INTEGER NOT NULL REFERENCES workflow_run(id) ON DELETE CASCADE,
  workflow_job_id INTEGER REFERENCES workflow_job(id) ON DELETE SET NULL,
  request_id TEXT NOT NULL DEFAULT '',
  work_id INTEGER NOT NULL REFERENCES work(id) ON DELETE CASCADE,
  remote_source_id INTEGER NOT NULL REFERENCES file_source(id) ON DELETE CASCADE,
  local_source_id INTEGER NOT NULL REFERENCES file_source(id) ON DELETE CASCADE,
  edition_code TEXT NOT NULL,
  target_root TEXT NOT NULL,
  staging_root TEXT NOT NULL,
  backup_root TEXT NOT NULL DEFAULT '',
  state TEXT NOT NULL DEFAULT 'planned',
  plan_json TEXT NOT NULL DEFAULT '{}',
  error_message TEXT NOT NULL DEFAULT '',
  published_at TEXT,
  registered_at TEXT,
  completed_at TEXT,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, staging_cleaned_at TEXT,
  UNIQUE(workflow_run_id)
);

CREATE TABLE remote_fetch_manifest_item (
  id INTEGER PRIMARY KEY,
  manifest_id INTEGER NOT NULL REFERENCES remote_fetch_manifest(id) ON DELETE CASCADE,
  relative_path TEXT NOT NULL,
  target_path TEXT NOT NULL,
  source_kind TEXT NOT NULL,
  action TEXT NOT NULL,
  expected_size_bytes INTEGER,
  content_hash TEXT NOT NULL DEFAULT '',
  state TEXT NOT NULL DEFAULT 'planned',
  error_message TEXT NOT NULL DEFAULT '',
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  remote_source_id INTEGER REFERENCES file_source(id) ON DELETE SET NULL,
  source_path TEXT NOT NULL DEFAULT '',
  original_target_path TEXT NOT NULL DEFAULT '',
  resolution TEXT NOT NULL DEFAULT 'auto',
  UNIQUE(manifest_id, target_path)
);

CREATE TABLE remote_fetch_request (
  request_id TEXT PRIMARY KEY,
  source_id INTEGER NOT NULL REFERENCES file_source(id) ON DELETE CASCADE,
  work_code TEXT NOT NULL,
  workflow_run_id INTEGER NOT NULL REFERENCES workflow_run(id) ON DELETE CASCADE,
  result_json TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE tag (
  id INTEGER PRIMARY KEY,
  namespace TEXT NOT NULL,
  normalized_name TEXT NOT NULL,
  display_name TEXT NOT NULL,
  language TEXT NOT NULL DEFAULT '',
  is_user_defined INTEGER NOT NULL DEFAULT 0 CHECK(is_user_defined IN (0, 1)),
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(namespace, normalized_name, language)
);

CREATE TABLE user_account (
  id INTEGER PRIMARY KEY,
  username TEXT NOT NULL UNIQUE,
  display_name TEXT NOT NULL DEFAULT '',
  role TEXT NOT NULL CHECK(role IN ('super_admin', 'admin', 'user')),
  enabled INTEGER NOT NULL DEFAULT 1,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
, ui_locale TEXT NOT NULL DEFAULT 'auto'
  CHECK(ui_locale IN ('auto', 'en', 'zh-Hans', 'zh-Hant', 'ja', 'ko')));

CREATE TABLE user_media_lyrics_preference (
  user_id INTEGER NOT NULL REFERENCES user_account(id) ON DELETE CASCADE,
  audio_media_item_id INTEGER NOT NULL REFERENCES media_item(id) ON DELETE CASCADE,
  lyrics_media_item_id INTEGER NOT NULL REFERENCES media_item(id) ON DELETE CASCADE,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY(user_id, audio_media_item_id),
  CHECK(audio_media_item_id <> lyrics_media_item_id)
);

CREATE TABLE user_media_progress (
  user_id INTEGER NOT NULL REFERENCES user_account(id) ON DELETE CASCADE,
  media_item_id INTEGER NOT NULL REFERENCES media_item(id) ON DELETE CASCADE,
  position_seconds REAL NOT NULL DEFAULT 0,
  duration_seconds REAL,
  completed INTEGER NOT NULL DEFAULT 0,
  last_played_at TEXT,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY(user_id, media_item_id)
);

CREATE TABLE user_party_state (
  user_id INTEGER NOT NULL REFERENCES user_account(id) ON DELETE CASCADE,
  party_id INTEGER NOT NULL REFERENCES party(id) ON DELETE CASCADE,
  rating INTEGER,
  note TEXT NOT NULL DEFAULT '',
  favorite INTEGER NOT NULL DEFAULT 0,
  last_viewed_at TEXT,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY(user_id, party_id)
);

CREATE TABLE user_party_tag (
  id INTEGER PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES user_account(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  color TEXT NOT NULL DEFAULT '',
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(user_id, name)
);

CREATE TABLE user_party_tag_assignment (
  user_id INTEGER NOT NULL REFERENCES user_account(id) ON DELETE CASCADE,
  party_id INTEGER NOT NULL REFERENCES party(id) ON DELETE CASCADE,
  user_party_tag_id INTEGER NOT NULL REFERENCES user_party_tag(id) ON DELETE CASCADE,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY(user_id, party_id, user_party_tag_id)
);

CREATE TABLE user_password_credential (
  user_id INTEGER PRIMARY KEY REFERENCES user_account(id) ON DELETE CASCADE,
  password_hash TEXT NOT NULL,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE user_person_state (
  user_id INTEGER NOT NULL REFERENCES user_account(id) ON DELETE CASCADE,
  person_id INTEGER NOT NULL REFERENCES person(id) ON DELETE CASCADE,
  rating INTEGER,
  note TEXT NOT NULL DEFAULT '',
  favorite INTEGER NOT NULL DEFAULT 0,
  last_viewed_at TEXT,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY(user_id, person_id)
);

CREATE TABLE user_person_tag (
  id INTEGER PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES user_account(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  color TEXT NOT NULL DEFAULT '',
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(user_id, name)
);

CREATE TABLE user_person_tag_assignment (
  user_id INTEGER NOT NULL REFERENCES user_account(id) ON DELETE CASCADE,
  person_id INTEGER NOT NULL REFERENCES person(id) ON DELETE CASCADE,
  user_person_tag_id INTEGER NOT NULL REFERENCES user_person_tag(id) ON DELETE CASCADE,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY(user_id, person_id, user_person_tag_id)
);

CREATE TABLE user_session (
  id TEXT PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES user_account(id) ON DELETE CASCADE,
  expires_at TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE user_tag (
  id INTEGER PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES user_account(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  color TEXT NOT NULL DEFAULT '',
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(user_id, name)
);

CREATE TABLE user_work_playback_cursor (
  user_id INTEGER NOT NULL REFERENCES user_account(id) ON DELETE CASCADE,
  work_id INTEGER NOT NULL REFERENCES work(id) ON DELETE CASCADE,
  media_item_id INTEGER NOT NULL REFERENCES media_item(id) ON DELETE CASCADE,
  file_source_id INTEGER REFERENCES file_source(id) ON DELETE SET NULL,
  location_id INTEGER REFERENCES media_file_location(id) ON DELETE SET NULL,
  location_type TEXT NOT NULL DEFAULT '',
  position_seconds REAL NOT NULL DEFAULT 0,
  duration_seconds REAL,
  completed INTEGER NOT NULL DEFAULT 0,
  last_played_at TEXT,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY(user_id, work_id)
);

CREATE TABLE user_work_state (
  user_id INTEGER NOT NULL REFERENCES user_account(id) ON DELETE CASCADE,
  work_id INTEGER NOT NULL REFERENCES work(id) ON DELETE CASCADE,
  listening_status TEXT NOT NULL DEFAULT 'none' CHECK(listening_status IN ('none', 'want_to_listen', 'listening', 'finished', 'relisten', 'paused')),
  favorite INTEGER NOT NULL DEFAULT 0,
  rating INTEGER,
  note TEXT NOT NULL DEFAULT '',
  last_played_at TEXT,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY(user_id, work_id)
);

CREATE TABLE user_work_tag (
  user_id INTEGER NOT NULL REFERENCES user_account(id) ON DELETE CASCADE,
  work_id INTEGER NOT NULL REFERENCES work(id) ON DELETE CASCADE,
  user_tag_id INTEGER NOT NULL REFERENCES user_tag(id) ON DELETE CASCADE,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY(user_id, work_id, user_tag_id)
);

CREATE TABLE voice_catalog_item (
  id INTEGER PRIMARY KEY,
  person_id INTEGER NOT NULL REFERENCES person(id) ON DELETE CASCADE,
  primary_code TEXT NOT NULL,
  work_id INTEGER REFERENCES work(id) ON DELETE SET NULL,
  title TEXT NOT NULL DEFAULT '',
  release_date TEXT,
  cover_url TEXT NOT NULL DEFAULT '',
  source_url TEXT NOT NULL DEFAULT '',
  circle TEXT NOT NULL DEFAULT '',
  age_rating TEXT NOT NULL DEFAULT '',
  rating_average REAL,
  rating_count INTEGER,
  sales_count INTEGER,
  current_price INTEGER,
  tags_json TEXT NOT NULL DEFAULT '[]',
  voice_actors_json TEXT NOT NULL DEFAULT '[]',
  raw_json TEXT NOT NULL DEFAULT '{}',
  catalog_status TEXT NOT NULL DEFAULT 'catalog',
  snapshot_generation INTEGER NOT NULL DEFAULT 0,
  last_seen_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(person_id, primary_code)
);

CREATE TABLE voice_catalog_refresh_state (
  person_id INTEGER PRIMARY KEY REFERENCES person(id) ON DELETE CASCADE,
  generation INTEGER NOT NULL DEFAULT 0,
  query_json TEXT NOT NULL DEFAULT '[]',
  source_status_json TEXT NOT NULL DEFAULT '[]',
  last_success_at TEXT,
  last_attempt_at TEXT,
  last_status TEXT NOT NULL DEFAULT '',
  last_run_id INTEGER REFERENCES workflow_run(id) ON DELETE SET NULL,
  last_error TEXT NOT NULL DEFAULT '',
  complete INTEGER NOT NULL DEFAULT 0,
  pages_fetched INTEGER NOT NULL DEFAULT 0,
  catalog_works INTEGER NOT NULL DEFAULT 0,
  metadata_queued INTEGER NOT NULL DEFAULT 0,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE voice_catalog_source (
  id INTEGER PRIMARY KEY,
  catalog_item_id INTEGER NOT NULL REFERENCES voice_catalog_item(id) ON DELETE CASCADE,
  provider_id INTEGER NOT NULL REFERENCES metadata_provider(id),
  remote_id TEXT NOT NULL DEFAULT '',
  remote_code TEXT NOT NULL,
  source_url TEXT NOT NULL DEFAULT '',
  availability TEXT NOT NULL DEFAULT 'unknown',
  raw_json TEXT NOT NULL DEFAULT '{}',
  snapshot_generation INTEGER NOT NULL DEFAULT 0,
  last_seen_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  last_checked_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(catalog_item_id, provider_id, remote_code)
);

CREATE TABLE work (
  id INTEGER PRIMARY KEY,
  primary_code TEXT NOT NULL UNIQUE,
  work_type TEXT NOT NULL DEFAULT 'audio',
  title TEXT NOT NULL,
  title_kana TEXT NOT NULL DEFAULT '',
  description TEXT NOT NULL DEFAULT '',
  release_date TEXT,
  age_rating TEXT NOT NULL DEFAULT '',
  cover_asset_id INTEGER,
  duration_seconds INTEGER,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
, rating_average REAL, sales_count INTEGER CHECK(sales_count IS NULL OR sales_count >= 0), regular_price INTEGER CHECK(regular_price IS NULL OR regular_price >= 0), current_price INTEGER CHECK(current_price IS NULL OR current_price >= 0), price_currency TEXT NOT NULL DEFAULT '', is_permanently_free INTEGER CHECK(is_permanently_free IS NULL OR is_permanently_free IN (0, 1)));

CREATE TABLE work_code_alias (
  id INTEGER PRIMARY KEY,
  logical_work_id INTEGER NOT NULL REFERENCES logical_work(id) ON DELETE CASCADE,
  provider_id INTEGER NOT NULL REFERENCES metadata_provider(id),
  primary_code TEXT NOT NULL,
  metadata_language TEXT NOT NULL DEFAULT '',
  edition_label TEXT NOT NULL DEFAULT '',
  source_work_id INTEGER REFERENCES work(id) ON DELETE SET NULL,
  relationship_kind TEXT NOT NULL DEFAULT 'provider_declared',
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(provider_id, primary_code)
);

CREATE TABLE work_credit (
  work_id INTEGER NOT NULL REFERENCES work(id) ON DELETE CASCADE,
  person_id INTEGER NOT NULL REFERENCES person(id) ON DELETE CASCADE,
  role TEXT NOT NULL,
  provider_id INTEGER REFERENCES metadata_provider(id),
  source TEXT NOT NULL DEFAULT '',
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY(work_id, person_id, role)
);

CREATE TABLE work_edition (
  work_id INTEGER PRIMARY KEY REFERENCES work(id) ON DELETE CASCADE,
  logical_work_id INTEGER NOT NULL REFERENCES logical_work(id) ON DELETE CASCADE,
  provider_id INTEGER REFERENCES metadata_provider(id),
  primary_code TEXT NOT NULL,
  base_code TEXT NOT NULL DEFAULT '',
  metadata_language TEXT NOT NULL DEFAULT '',
  edition_label TEXT NOT NULL DEFAULT '',
  is_canonical INTEGER NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
, translation_kind TEXT NOT NULL DEFAULT 'unknown', classification_source TEXT NOT NULL DEFAULT '', maker_id TEXT NOT NULL DEFAULT '', origin_maker_id TEXT NOT NULL DEFAULT '');

CREATE TABLE work_external_id (
  id INTEGER PRIMARY KEY,
  work_id INTEGER NOT NULL REFERENCES work(id) ON DELETE CASCADE,
  provider_id INTEGER NOT NULL REFERENCES metadata_provider(id),
  id_type TEXT NOT NULL,
  external_id TEXT NOT NULL,
  url TEXT NOT NULL DEFAULT '',
  is_primary INTEGER NOT NULL DEFAULT 0,
  UNIQUE(provider_id, id_type, external_id)
);

CREATE TABLE work_folder_location (
  id INTEGER PRIMARY KEY,
  work_id INTEGER NOT NULL REFERENCES work(id) ON DELETE CASCADE,
  file_source_id INTEGER NOT NULL REFERENCES file_source(id) ON DELETE CASCADE,
  root_path TEXT NOT NULL,
  role TEXT NOT NULL DEFAULT 'external',
  origin_source_id INTEGER REFERENCES file_source(id) ON DELETE SET NULL,
  origin_remote_code TEXT NOT NULL DEFAULT '',
  state TEXT NOT NULL DEFAULT 'active',
  is_primary INTEGER NOT NULL DEFAULT 0,
  last_scanned_at TEXT,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, cleanup_run_id INTEGER REFERENCES workflow_run(id) ON DELETE SET NULL,
  UNIQUE(file_source_id, root_path)
);

CREATE TABLE work_manual_override (
  work_id INTEGER NOT NULL REFERENCES work(id) ON DELETE CASCADE,
  field_name TEXT NOT NULL,
  value_json TEXT NOT NULL DEFAULT 'null',
  asset_path TEXT NOT NULL DEFAULT '',
  updated_by_user_id INTEGER REFERENCES user_account(id) ON DELETE SET NULL,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY(work_id, field_name)
);

CREATE TABLE work_metadata_provider_state (
  work_id INTEGER NOT NULL REFERENCES work(id) ON DELETE CASCADE,
  provider_id INTEGER NOT NULL REFERENCES metadata_provider(id) ON DELETE CASCADE,
  status TEXT NOT NULL CHECK(status IN ('available', 'not_found')),
  message TEXT NOT NULL DEFAULT '',
  checked_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY(work_id, provider_id)
);

CREATE TABLE work_party (
  work_id INTEGER NOT NULL REFERENCES work(id) ON DELETE CASCADE,
  party_id INTEGER NOT NULL REFERENCES party(id) ON DELETE CASCADE,
  role TEXT NOT NULL DEFAULT 'circle',
  provider_id INTEGER REFERENCES metadata_provider(id),
  source TEXT NOT NULL DEFAULT '',
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY(work_id, party_id, role)
);

CREATE TABLE work_source_presence (
  work_id INTEGER NOT NULL REFERENCES work(id) ON DELETE CASCADE,
  file_source_id INTEGER NOT NULL REFERENCES file_source(id) ON DELETE CASCADE,
  presence_type TEXT NOT NULL DEFAULT 'location',
  remote_id TEXT NOT NULL DEFAULT '',
  remote_code TEXT NOT NULL DEFAULT '',
  source_url TEXT NOT NULL DEFAULT '',
  availability TEXT NOT NULL DEFAULT 'unknown',
  raw_json TEXT NOT NULL DEFAULT '{}',
  last_seen_at TEXT,
  last_checked_at TEXT,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY(work_id, file_source_id, presence_type)
);

CREATE TABLE work_tag (
  work_id INTEGER NOT NULL REFERENCES work(id) ON DELETE CASCADE,
  tag_id INTEGER NOT NULL REFERENCES tag(id) ON DELETE CASCADE,
  source TEXT NOT NULL DEFAULT '',
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY(work_id, tag_id, source)
);

CREATE TABLE workflow_candidate (
  id INTEGER PRIMARY KEY,
  workflow_run_id INTEGER NOT NULL REFERENCES workflow_run(id) ON DELETE CASCADE,
  workflow_node_run_id INTEGER REFERENCES workflow_node_run(id) ON DELETE SET NULL,
  candidate_type TEXT NOT NULL,
  external_key TEXT NOT NULL DEFAULT '',
  status TEXT NOT NULL,
  payload_json TEXT NOT NULL DEFAULT '{}',
  decision_json TEXT NOT NULL DEFAULT '{}',
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE workflow_definition (
  id INTEGER PRIMARY KEY,
  code TEXT NOT NULL UNIQUE,
  display_name TEXT NOT NULL,
  description TEXT NOT NULL DEFAULT '',
  definition_json TEXT NOT NULL DEFAULT '{}',
  scope TEXT NOT NULL DEFAULT 'system' CHECK(scope IN ('system', 'user')),
  editable INTEGER NOT NULL DEFAULT 0 CHECK(editable IN (0, 1)),
  owner_user_id INTEGER REFERENCES user_account(id) ON DELETE SET NULL,
  created_by_user_id INTEGER REFERENCES user_account(id) ON DELETE SET NULL,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE workflow_event (
  id INTEGER PRIMARY KEY,
  workflow_run_id INTEGER NOT NULL REFERENCES workflow_run(id) ON DELETE CASCADE,
  workflow_node_run_id INTEGER REFERENCES workflow_node_run(id) ON DELETE SET NULL,
  workflow_job_id INTEGER REFERENCES workflow_job(id) ON DELETE SET NULL,
  level TEXT NOT NULL DEFAULT 'info',
  event_type TEXT NOT NULL,
  message TEXT NOT NULL,
  detail_json TEXT NOT NULL DEFAULT '{}',
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE workflow_job (
  id INTEGER PRIMARY KEY,
  workflow_run_id INTEGER NOT NULL REFERENCES workflow_run(id) ON DELETE CASCADE,
  workflow_node_run_id INTEGER REFERENCES workflow_node_run(id) ON DELETE SET NULL,
  worker_type TEXT NOT NULL,
  status TEXT NOT NULL,
  payload_json TEXT NOT NULL DEFAULT '{}',
  retry_count INTEGER NOT NULL DEFAULT 0,
  error_message TEXT NOT NULL DEFAULT '',
  progress_current INTEGER NOT NULL DEFAULT 0,
  progress_total INTEGER NOT NULL DEFAULT 0,
  locked_by TEXT NOT NULL DEFAULT '',
  locked_at TEXT,
  heartbeat_at TEXT,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
, checkpoint_json TEXT NOT NULL DEFAULT '{}', recoverable INTEGER NOT NULL DEFAULT 0, max_retries INTEGER NOT NULL DEFAULT 3, resume_count INTEGER NOT NULL DEFAULT 0, available_at TEXT, priority INTEGER NOT NULL DEFAULT 0, resource_key TEXT NOT NULL DEFAULT '', progress_bytes_current INTEGER NOT NULL DEFAULT 0 CHECK(progress_bytes_current >= 0), progress_bytes_total INTEGER NOT NULL DEFAULT 0 CHECK(progress_bytes_total >= 0), progress_bytes_unknown_items INTEGER NOT NULL DEFAULT 0 CHECK(progress_bytes_unknown_items >= 0));

CREATE TABLE workflow_node_run (
  id INTEGER PRIMARY KEY,
  workflow_run_id INTEGER NOT NULL REFERENCES workflow_run(id) ON DELETE CASCADE,
  node_id TEXT NOT NULL,
  node_type TEXT NOT NULL,
  display_name TEXT NOT NULL,
  position INTEGER NOT NULL DEFAULT 0,
  status TEXT NOT NULL,
  input_json TEXT NOT NULL DEFAULT '{}',
  output_json TEXT NOT NULL DEFAULT '{}',
  error_message TEXT NOT NULL DEFAULT '',
  started_at TEXT,
  finished_at TEXT,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE workflow_notification (
  id INTEGER PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES user_account(id) ON DELETE CASCADE,
  workflow_run_id INTEGER NOT NULL REFERENCES workflow_run(id) ON DELETE CASCADE,
  notification_type TEXT NOT NULL,
  status TEXT NOT NULL,
  work_id INTEGER REFERENCES work(id) ON DELETE SET NULL,
  work_code TEXT NOT NULL DEFAULT '',
  message TEXT NOT NULL DEFAULT '',
  dismissed_at TEXT,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(user_id, workflow_run_id, notification_type)
);

CREATE TABLE workflow_run (
  id INTEGER PRIMARY KEY,
  workflow_definition_id INTEGER REFERENCES workflow_definition(id) ON DELETE SET NULL,
  trigger_id INTEGER REFERENCES workflow_trigger(id) ON DELETE SET NULL,
  workflow_code TEXT NOT NULL,
  display_name TEXT NOT NULL,
  status TEXT NOT NULL,
  trigger_type TEXT NOT NULL,
  trigger_reason TEXT NOT NULL DEFAULT '',
  input_json TEXT NOT NULL DEFAULT '{}',
  summary_json TEXT NOT NULL DEFAULT '{}',
  started_at TEXT,
  finished_at TEXT,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE workflow_run_review (
  id INTEGER PRIMARY KEY,
  workflow_run_id INTEGER NOT NULL REFERENCES workflow_run(id) ON DELETE CASCADE,
  user_id INTEGER NOT NULL REFERENCES user_account(id) ON DELETE CASCADE,
  status TEXT NOT NULL DEFAULT 'reviewed',
  note TEXT NOT NULL DEFAULT '',
  reviewed_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(workflow_run_id, user_id)
);

CREATE TABLE workflow_trigger (
  id INTEGER PRIMARY KEY,
  workflow_definition_id INTEGER NOT NULL REFERENCES workflow_definition(id) ON DELETE CASCADE,
  trigger_type TEXT NOT NULL,
  display_name TEXT NOT NULL,
  enabled INTEGER NOT NULL DEFAULT 1,
  schedule_json TEXT NOT NULL DEFAULT '{}',
  config_json TEXT NOT NULL DEFAULT '{}',
  next_run_at TEXT,
  last_run_at TEXT,
  last_success_at TEXT,
  last_error_message TEXT NOT NULL DEFAULT '',
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO "metadata_provider" ("id", "code", "display_name") VALUES (1, 'manual', 'Manual');
INSERT INTO "metadata_provider" ("id", "code", "display_name") VALUES (2, 'dlsite', 'DLsite');
INSERT INTO "recommendation_input_revision" ("id", "revision") VALUES (1, 0);
INSERT INTO "workflow_definition" ("id", "code", "display_name", "description", "definition_json", "scope", "editable", "owner_user_id", "created_by_user_id") VALUES (2, 'local_library_scan', 'Scan local library', 'Discover local works and synchronize local source presence.', '{"nodes":[{"id":"select","type":"select_local_source","displayName":"Select local source"},{"id":"discover","type":"discover_local_files","displayName":"Discover files"},{"id":"match","type":"match_works","displayName":"Match works"},{"id":"sync","type":"sync_file_locations","displayName":"Sync locations"}]}', 'system', 0, NULL, NULL);
INSERT INTO "workflow_definition" ("id", "code", "display_name", "description", "definition_json", "scope", "editable", "owner_user_id", "created_by_user_id") VALUES (3, 'metadata_sync', 'Sync work metadata', 'Select works and sync normalized metadata snapshots.', '{"nodes":[{"id":"select","type":"select_works"},{"id":"sync","type":"sync_metadata"}]}', 'system', 0, NULL, NULL);
INSERT INTO "workflow_definition" ("id", "code", "display_name", "description", "definition_json", "scope", "editable", "owner_user_id", "created_by_user_id") VALUES (4, 'remote_source_sync', 'Sync remote source', 'Discover remote works, filter candidates, match works, and sync remote locations.', '{"nodes":[{"id":"select","type":"select_remote_source"},{"id":"discover","type":"discover_remote_works"},{"id":"filter","type":"filter_candidates"},{"id":"match","type":"match_works"},{"id":"sync","type":"sync_file_locations"}]}', 'system', 0, NULL, NULL);
INSERT INTO "workflow_definition" ("id", "code", "display_name", "description", "definition_json", "scope", "editable", "owner_user_id", "created_by_user_id") VALUES (5, 'media_cache', 'Cache media', 'Select media items, filter cache misses, sync source state, and materialize cache files.', '{"nodes":[{"id":"select","type":"select_media_items"},{"id":"filter","type":"filter_candidates"},{"id":"sync","type":"sync_file_locations"},{"id":"cache","type":"materialize_cache"}]}', 'system', 0, NULL, NULL);
INSERT INTO "workflow_definition" ("id", "code", "display_name", "description", "definition_json", "scope", "editable", "owner_user_id", "created_by_user_id") VALUES (6, 'media_save', 'Save media to local library', 'Select media items or folders, sync source state, cache when needed, and save to a local source.', '{"nodes":[{"id":"select","type":"select_media_items"},{"id":"filter","type":"filter_candidates"},{"id":"sync","type":"sync_file_locations"},{"id":"cache","type":"materialize_cache"},{"id":"save","type":"materialize_save"}]}', 'system', 0, NULL, NULL);
INSERT INTO "workflow_trigger" ("id", "workflow_definition_id", "trigger_type", "display_name", "enabled", "schedule_json", "config_json", "next_run_at", "last_run_at", "last_success_at", "last_error_message") VALUES (1, 2, 'startup', 'Startup local library scan', 1, '{"type":"startup"}', '{"followUpRun":false}', NULL, NULL, NULL, '');
INSERT INTO "workflow_trigger" ("id", "workflow_definition_id", "trigger_type", "display_name", "enabled", "schedule_json", "config_json", "next_run_at", "last_run_at", "last_success_at", "last_error_message") VALUES (2, 2, 'filesystem_event', 'Watch data folders', 1, '{"type":"filesystem_event"}', '{"followUpRun":false}', NULL, NULL, NULL, '');
INSERT INTO "filesystem_trigger_state" ("trigger_id", "watched_directory_count", "last_event_at") VALUES (2, 0, NULL);

CREATE INDEX idx_availability_watch_outbox_pending
ON availability_watch_outbox(status, next_attempt_at, id);

CREATE INDEX idx_availability_watch_target_due
ON availability_watch_target(active, state, next_check_at, id);

CREATE UNIQUE INDEX idx_favorite_list_one_marked_per_user
  ON favorite_list(user_id)
  WHERE kind = 'marked';

CREATE INDEX idx_favorite_list_user_kind_sort
  ON favorite_list(user_id, kind, sort_order, id);

CREATE UNIQUE INDEX idx_file_source_endpoint_source
  ON file_source_endpoint(file_source_id);

CREATE INDEX idx_media_file_location_cache_lru
  ON media_file_location(location_type, availability, file_source_id, last_checked_at);

CREATE INDEX idx_media_file_location_item_source_type
  ON media_file_location(media_item_id, file_source_id, location_type, path);

CREATE INDEX idx_media_file_location_path_lookup
  ON media_file_location(file_source_id, location_type, path, size_bytes, availability);

CREATE INDEX idx_media_file_location_source_type_availability
  ON media_file_location(file_source_id, location_type, availability, last_checked_at);

CREATE INDEX idx_media_item_fingerprint
  ON media_item(fingerprint);

CREATE INDEX idx_media_item_work
  ON media_item(work_id, parent_id, kind, track_no, title);

CREATE INDEX idx_metadata_snapshot_provider_external_latest
  ON metadata_snapshot(provider_id, external_id, fetched_at DESC, id DESC);

CREATE INDEX idx_metadata_snapshot_work_provider_latest
  ON metadata_snapshot(work_id, provider_id, fetched_at DESC, id DESC);

CREATE INDEX idx_party_catalog_party
  ON party_catalog_item(party_id, last_seen_at DESC);

CREATE INDEX idx_party_external_id_lookup
  ON party_external_id(provider_id, id_type, external_id);

CREATE INDEX idx_party_metadata_snapshot_party_provider_latest
  ON party_metadata_snapshot(party_id, provider_id, fetched_at DESC, id DESC);

CREATE INDEX idx_party_series_party
  ON party_series(party_id, provider_id);

CREATE INDEX idx_party_series_work_code_upper
  ON party_series_work(UPPER(primary_code), series_id);

CREATE INDEX idx_person_external_id_person
  ON person_external_id(person_id, provider_id);

CREATE INDEX idx_person_merge_review_target
  ON person_merge_review(target_person_id, status, created_at);

CREATE INDEX idx_recommendation_client_session_generation
  ON recommendation_client_session(generation_id);

CREATE INDEX idx_recommendation_event_type_created
  ON recommendation_event(event_type, created_at DESC, id DESC);

CREATE INDEX idx_recommendation_event_user_created
  ON recommendation_event(user_id, created_at DESC, id DESC);

CREATE INDEX idx_recommendation_generation_user_created
  ON recommendation_generation(user_id, created_at DESC, id DESC);

CREATE INDEX idx_recommendation_snapshot_work_generation
  ON recommendation_snapshot(work_id, generation_id);

CREATE INDEX idx_remote_fetch_manifest_item_source
  ON remote_fetch_manifest_item(manifest_id, remote_source_id, state, id);

CREATE INDEX idx_remote_fetch_manifest_item_state
  ON remote_fetch_manifest_item(manifest_id, state, id);

CREATE INDEX idx_remote_fetch_manifest_staging_cleanup
  ON remote_fetch_manifest(staging_cleaned_at, state, updated_at, workflow_run_id);

CREATE INDEX idx_remote_fetch_manifest_state
  ON remote_fetch_manifest(state, updated_at);

CREATE INDEX idx_remote_fetch_request_created_at
  ON remote_fetch_request(created_at);

CREATE INDEX idx_remote_fetch_request_run
  ON remote_fetch_request(workflow_run_id);

CREATE INDEX idx_tag_namespace_display_name
  ON tag(namespace, display_name);

CREATE INDEX idx_user_media_lyrics_preference_lyrics
  ON user_media_lyrics_preference(lyrics_media_item_id, user_id);

CREATE INDEX idx_user_media_progress_user_latest
  ON user_media_progress(user_id, last_played_at DESC, updated_at DESC, media_item_id);

CREATE INDEX idx_user_work_playback_cursor_media
  ON user_work_playback_cursor(media_item_id, user_id);

CREATE INDEX idx_user_work_playback_cursor_recent
  ON user_work_playback_cursor(user_id, last_played_at DESC, work_id);

CREATE INDEX idx_voice_catalog_person_seen
  ON voice_catalog_item(person_id, last_seen_at DESC, primary_code);

CREATE INDEX idx_voice_catalog_source_item
  ON voice_catalog_source(catalog_item_id, availability, last_seen_at DESC);

CREATE INDEX idx_voice_catalog_source_refresh
  ON voice_catalog_source(provider_id, snapshot_generation, availability);

CREATE INDEX idx_work_code_alias_code_upper
  ON work_code_alias(UPPER(primary_code), provider_id, logical_work_id);

CREATE INDEX idx_work_code_alias_logical
  ON work_code_alias(logical_work_id, provider_id, primary_code);

CREATE INDEX idx_work_credit_person
  ON work_credit(person_id, role);

CREATE INDEX idx_work_demo_eligibility
  ON work(is_permanently_free, age_rating, id);

CREATE INDEX idx_work_edition_logical_work
  ON work_edition(logical_work_id, is_canonical DESC, primary_code);

CREATE INDEX idx_work_edition_primary_code_upper
  ON work_edition(UPPER(primary_code), logical_work_id);

CREATE UNIQUE INDEX idx_work_edition_provider_code
  ON work_edition(provider_id, primary_code);

CREATE INDEX idx_work_edition_translation_kind
  ON work_edition(logical_work_id, translation_kind, primary_code);

CREATE INDEX idx_work_folder_location_cleanup
  ON work_folder_location(cleanup_run_id, state, id);

CREATE INDEX idx_work_folder_location_work_state
  ON work_folder_location(work_id, state, is_primary DESC, updated_at DESC);

CREATE INDEX idx_work_manual_override_field
  ON work_manual_override(field_name, updated_at);

CREATE INDEX idx_work_metadata_provider_state_provider_status
  ON work_metadata_provider_state(provider_id, status, work_id);

CREATE INDEX idx_work_party_party
  ON work_party(party_id, role);

CREATE INDEX idx_work_primary_code_upper
  ON work(UPPER(primary_code));

CREATE INDEX idx_work_rating_average
  ON work(rating_average DESC, id DESC);

CREATE INDEX idx_work_sales_count
  ON work(sales_count DESC, id DESC);

CREATE INDEX idx_work_source_presence_source
  ON work_source_presence(file_source_id, availability, updated_at);

CREATE INDEX idx_work_tag_tag_work
  ON work_tag(tag_id, work_id);

CREATE INDEX idx_workflow_candidate_run
  ON workflow_candidate(workflow_run_id);

CREATE INDEX idx_workflow_candidate_status
  ON workflow_candidate(status);

CREATE INDEX idx_workflow_definition_owner
  ON workflow_definition(owner_user_id);

CREATE INDEX idx_workflow_definition_scope
  ON workflow_definition(scope, editable);

CREATE INDEX idx_workflow_event_level
  ON workflow_event(level, created_at);

CREATE INDEX idx_workflow_event_run
  ON workflow_event(workflow_run_id, created_at, id);

CREATE INDEX idx_workflow_event_run_id
  ON workflow_event(workflow_run_id, id);

CREATE INDEX idx_workflow_job_claim_priority
  ON workflow_job(status, priority DESC, available_at, created_at, id);

CREATE INDEX idx_workflow_job_node_run
  ON workflow_job(workflow_node_run_id);

CREATE INDEX idx_workflow_job_recovery
  ON workflow_job(status, recoverable, available_at, heartbeat_at, id);

CREATE INDEX idx_workflow_job_resource_status
ON workflow_job(resource_key, status, priority DESC, created_at, id);

CREATE INDEX idx_workflow_job_run
  ON workflow_job(workflow_run_id);

CREATE INDEX idx_workflow_node_run_run
  ON workflow_node_run(workflow_run_id, position);

CREATE INDEX idx_workflow_node_run_status
  ON workflow_node_run(status);

CREATE INDEX idx_workflow_notification_user_active
  ON workflow_notification(user_id, dismissed_at, created_at DESC, id DESC);

CREATE INDEX idx_workflow_run_created_at
  ON workflow_run(created_at);

CREATE INDEX idx_workflow_run_review_run
  ON workflow_run_review(workflow_run_id);

CREATE INDEX idx_workflow_run_review_user
  ON workflow_run_review(user_id, reviewed_at);

CREATE INDEX idx_workflow_run_status
  ON workflow_run(status);

CREATE INDEX idx_workflow_trigger_enabled_type
  ON workflow_trigger(enabled, trigger_type);

CREATE UNIQUE INDEX idx_workflow_trigger_filesystem_definition
  ON workflow_trigger(workflow_definition_id)
  WHERE trigger_type = 'filesystem_event';

CREATE VIEW work_primary_circle AS
WITH family_target AS (
  SELECT
    work.id AS work_id,
    COALESCE(logical.canonical_work_id, work.id) AS canonical_work_id
  FROM work
  LEFT JOIN work_edition AS edition ON edition.work_id = work.id
  LEFT JOIN logical_work AS logical ON logical.id = edition.logical_work_id
), ranked AS (
  SELECT
    target.work_id,
    relation.party_id,
    party.display_name,
    COALESCE(external.external_id, '') AS external_id,
    relation.role,
    relation.source,
    ROW_NUMBER() OVER (
      PARTITION BY target.work_id
      ORDER BY
        CASE
          WHEN relation.work_id = target.work_id AND relation.source = 'manual_override' THEN 0
          WHEN relation.work_id = target.canonical_work_id AND relation.source = 'manual_override' THEN 1
          WHEN relation.work_id = target.canonical_work_id
            AND edition.maker_id <> ''
            AND UPPER(COALESCE(external.external_id, '')) = UPPER(edition.maker_id) THEN 2
          WHEN relation.work_id = target.canonical_work_id
            AND relation_provider.code = 'dlsite'
            AND relation.source IN ('dlsite_snapshot', 'dlsite_product', 'dlsite_edition') THEN 3
          WHEN relation.work_id = target.canonical_work_id
            AND relation_provider.code = 'dlsite' THEN 4
          WHEN edition.maker_id <> ''
            AND UPPER(COALESCE(external.external_id, '')) = UPPER(edition.maker_id) THEN 5
          WHEN relation_provider.code = 'dlsite'
            AND relation.source IN ('dlsite_snapshot', 'dlsite_product', 'dlsite_edition') THEN 6
          WHEN relation_provider.code = 'dlsite' THEN 7
          WHEN relation.source = 'remote_source' THEN 9
          ELSE 8
        END,
        relation.party_id ASC
    ) AS position
  FROM family_target AS target
  INNER JOIN work_party AS relation
    ON relation.work_id = target.work_id
    OR relation.work_id = target.canonical_work_id
  INNER JOIN party ON party.id = relation.party_id
  LEFT JOIN work_edition AS edition ON edition.work_id = relation.work_id
  LEFT JOIN metadata_provider AS relation_provider ON relation_provider.id = relation.provider_id
  LEFT JOIN party_external_id AS external ON external.id = (
    SELECT candidate.id
    FROM party_external_id AS candidate
    LEFT JOIN metadata_provider AS candidate_provider ON candidate_provider.id = candidate.provider_id
    WHERE candidate.party_id = party.id
    ORDER BY
      CASE WHEN candidate_provider.code = 'dlsite' THEN 0 ELSE 1 END,
      candidate.is_primary DESC,
      candidate.id ASC
    LIMIT 1
  )
  WHERE relation.role = 'circle'
)
SELECT work_id, party_id, display_name, external_id, role, source
FROM ranked
WHERE position = 1;

CREATE TRIGGER recommendation_revision_config_delete
AFTER DELETE ON app_setting
WHEN OLD.key = 'recommendation_config'
BEGIN
  UPDATE recommendation_input_revision
  SET revision = revision + 1, updated_at = CURRENT_TIMESTAMP
  WHERE id = 1;
END;

CREATE TRIGGER recommendation_revision_config_insert
AFTER INSERT ON app_setting
WHEN NEW.key = 'recommendation_config'
BEGIN
  UPDATE recommendation_input_revision
  SET revision = revision + 1, updated_at = CURRENT_TIMESTAMP
  WHERE id = 1;
END;

CREATE TRIGGER recommendation_revision_config_update
AFTER UPDATE OF value_json ON app_setting
WHEN NEW.key = 'recommendation_config' AND NEW.value_json <> OLD.value_json
BEGIN
  UPDATE recommendation_input_revision
  SET revision = revision + 1, updated_at = CURRENT_TIMESTAMP
  WHERE id = 1;
END;

CREATE TRIGGER recommendation_revision_tag_namespace_update
AFTER UPDATE OF namespace ON tag
BEGIN
  UPDATE recommendation_input_revision
  SET revision = revision + 1, updated_at = CURRENT_TIMESTAMP
  WHERE id = 1;
END;

CREATE TRIGGER recommendation_revision_user_state_delete
AFTER DELETE ON user_work_state
BEGIN
  UPDATE recommendation_user_revision
  SET revision = revision + 1, updated_at = CURRENT_TIMESTAMP
  WHERE user_id = OLD.user_id;
END;

CREATE TRIGGER recommendation_revision_user_state_insert
AFTER INSERT ON user_work_state
BEGIN
  INSERT INTO recommendation_user_revision (user_id, revision, updated_at)
  VALUES (NEW.user_id, 1, CURRENT_TIMESTAMP)
  ON CONFLICT(user_id) DO UPDATE SET
    revision = recommendation_user_revision.revision + 1,
    updated_at = CURRENT_TIMESTAMP;
END;

CREATE TRIGGER recommendation_revision_user_state_update
AFTER UPDATE OF listening_status, favorite ON user_work_state
BEGIN
  INSERT INTO recommendation_user_revision (user_id, revision, updated_at)
  VALUES (NEW.user_id, 1, CURRENT_TIMESTAMP)
  ON CONFLICT(user_id) DO UPDATE SET
    revision = recommendation_user_revision.revision + 1,
    updated_at = CURRENT_TIMESTAMP;
END;

CREATE TRIGGER recommendation_revision_work_credit_delete
AFTER DELETE ON work_credit
BEGIN
  UPDATE recommendation_input_revision
  SET revision = revision + 1, updated_at = CURRENT_TIMESTAMP
  WHERE id = 1;
END;

CREATE TRIGGER recommendation_revision_work_credit_insert
AFTER INSERT ON work_credit
BEGIN
  UPDATE recommendation_input_revision
  SET revision = revision + 1, updated_at = CURRENT_TIMESTAMP
  WHERE id = 1;
END;

CREATE TRIGGER recommendation_revision_work_credit_update
AFTER UPDATE ON work_credit
BEGIN
  UPDATE recommendation_input_revision
  SET revision = revision + 1, updated_at = CURRENT_TIMESTAMP
  WHERE id = 1;
END;

CREATE TRIGGER recommendation_revision_work_delete
AFTER DELETE ON work
BEGIN
  UPDATE recommendation_input_revision
  SET revision = revision + 1, updated_at = CURRENT_TIMESTAMP
  WHERE id = 1;
END;

CREATE TRIGGER recommendation_revision_work_insert
AFTER INSERT ON work
BEGIN
  UPDATE recommendation_input_revision
  SET revision = revision + 1, updated_at = CURRENT_TIMESTAMP
  WHERE id = 1;
END;

CREATE TRIGGER recommendation_revision_work_party_delete
AFTER DELETE ON work_party
BEGIN
  UPDATE recommendation_input_revision
  SET revision = revision + 1, updated_at = CURRENT_TIMESTAMP
  WHERE id = 1;
END;

CREATE TRIGGER recommendation_revision_work_party_insert
AFTER INSERT ON work_party
BEGIN
  UPDATE recommendation_input_revision
  SET revision = revision + 1, updated_at = CURRENT_TIMESTAMP
  WHERE id = 1;
END;

CREATE TRIGGER recommendation_revision_work_party_update
AFTER UPDATE ON work_party
BEGIN
  UPDATE recommendation_input_revision
  SET revision = revision + 1, updated_at = CURRENT_TIMESTAMP
  WHERE id = 1;
END;

CREATE TRIGGER recommendation_revision_work_tag_delete
AFTER DELETE ON work_tag
BEGIN
  UPDATE recommendation_input_revision
  SET revision = revision + 1, updated_at = CURRENT_TIMESTAMP
  WHERE id = 1;
END;

CREATE TRIGGER recommendation_revision_work_tag_insert
AFTER INSERT ON work_tag
BEGIN
  UPDATE recommendation_input_revision
  SET revision = revision + 1, updated_at = CURRENT_TIMESTAMP
  WHERE id = 1;
END;

CREATE TRIGGER recommendation_revision_work_tag_update
AFTER UPDATE ON work_tag
BEGIN
  UPDATE recommendation_input_revision
  SET revision = revision + 1, updated_at = CURRENT_TIMESTAMP
  WHERE id = 1;
END;

CREATE TRIGGER validate_workflow_definition_insert
BEFORE INSERT ON workflow_definition
BEGIN
  SELECT CASE
    WHEN NEW.scope = 'system' AND NEW.editable != 0
      THEN RAISE(ABORT, 'system workflow definitions are not editable')
    WHEN NEW.scope = 'system' AND NEW.owner_user_id IS NOT NULL
      THEN RAISE(ABORT, 'system workflow definitions cannot have an owner')
    WHEN NEW.scope = 'user' AND NEW.editable != 1
      THEN RAISE(ABORT, 'user workflow definitions must be editable')
  END;
END;

CREATE TRIGGER validate_workflow_definition_update
BEFORE UPDATE ON workflow_definition
BEGIN
  SELECT CASE
    WHEN NEW.scope = 'system' AND NEW.editable != 0
      THEN RAISE(ABORT, 'system workflow definitions are not editable')
    WHEN NEW.scope = 'system' AND NEW.owner_user_id IS NOT NULL
      THEN RAISE(ABORT, 'system workflow definitions cannot have an owner')
    WHEN NEW.scope = 'user' AND NEW.editable != 1
      THEN RAISE(ABORT, 'user workflow definitions must be editable')
  END;
END;

CREATE TRIGGER validate_workflow_trigger_insert
BEFORE INSERT ON workflow_trigger
BEGIN
  SELECT CASE
    WHEN NEW.trigger_type NOT IN ('startup', 'schedule', 'filesystem_event', 'source_poll')
      THEN RAISE(ABORT, 'invalid workflow trigger type')
  END;
END;

CREATE TRIGGER validate_workflow_trigger_update
BEFORE UPDATE ON workflow_trigger
BEGIN
  SELECT CASE
    WHEN NEW.trigger_type NOT IN ('startup', 'schedule', 'filesystem_event', 'source_poll')
      THEN RAISE(ABORT, 'invalid workflow trigger type')
  END;
END;
